name: test-secret

on:
  workflow_dispatch:
    inputs:
      secret_value:
        description: "Secret Value"
        required: true
        type: string

jobs:
  create_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: gliech/create-github-secret-action@v1
        with:
          name: "SECRET_${{ vars.GITHUB_RUN_NUMBER }}"
          value: ${{ inputs.secret_value }}
          pa_token: ${{ secrets.RTOKEN }}
